README.md
examples/complete/main.tf
main.tf
variables.tf

Fix for bucket policy count when value is not computed

---

main.tf

Made kms_master_key_id field optional.
Terraform allows to omit this field, and default `aws/s3` key will be used. Also AES256 sse algorithm can't be used with this field.

Mark kms_master_key_id as optional

---

.pre-commit-config.yaml
README.md
examples/complete/README.md
examples/complete/main.tf
examples/s3-replication/README.md
main.tf
variables.tf
versions.tf

Prior to this change, the module didn't have support for blocking public access check [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/access-control-block-public-access.html) and [here](https://www.terraform.io/docs/providers/aws/r/s3_bucket_public_access_block.html).
All the blocking defaults to `true` and can be adjusted with variables. Hopefully this PR resolves issues #7 and #17 .
New version can be tested with following example:
```
module "s3_bucket" {
source = "github.com/serhatcetinkaya/terraform-aws-s3-bucket?ref=aws_s3_bucket_public_access_block"
bucket = "my-s3-bucket-test-blocking-public-access"
acl    = "private"
versioning = {
enabled = true
}
}
```

Aws s3 bucket public access block

---

.pre-commit-config.yaml
README.md
examples/notification/README.md
examples/notification/main.tf
main.tf
modules/notification/main.tf
variables.tf

Add a bool which controls the creation of resource "aws_s3_bucket_public_access_block"
We have an environment where S3 buckets are being created under a role without `PutBucketPolicy`.
No, by default the behavior will remain the same.
Tested against a role without `PutBucketPolicy`.

feat: Added attach_public_policy as conditional switch

---

README.md
versions.tf

Update the required version block to allow 0.13 usage
This module cannot be used with the 0.13 versions of terraform (beta, or the upcoming GA), this modifies the version so that it can at least be used. However, there are other changes that might be desirable, such as deprecating the `create_bucket` argument now that module count will be available.
Forked this repo, changed the file, and ran through loading the module, changing count, and changing for_each.

chore: Allow 0.13

---

README.md
examples/s3-replication/main.tf
main.tf
variables.tf
versions.tf

The 3.0 aws provider does not allow a region parameter for the `aws_s3_bucket` resource.

feat: Remove region parameter for 3.0 aws provider

---

README.md
examples/complete/main.tf
main.tf
variables.tf

Modify CORS to support multiple rules instead of a single rule
When importing an existing bucket the module was attempting to remove all but one of the rules.
Yes
Object to Array. It is possible to be backwards compatible, however, since the syntax is as simple as adding brackets there is little reason to add additional code.
Applying on an existing resource

feat: support a list of rules instead of a single rule

---

main.tf

For required arguments instead of doing a lookup, variables are fixed. I fixed such arguments which are required instead of lookup.
Makes it easier to not miss these variables to set. Also, keeps the module uniform as other variables are set like this.
None
Plan against the [example/s3-replication](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/tree/master/examples/s3-replication).

fix: Using required arguments instead of lookup in replication_configuration

---

README.md
variables.tf

fix: Fixed grant variable type

---

README.md
examples/notification/README.md
examples/notification/main.tf
examples/notification/versions.tf
examples/s3-replication/README.md
examples/s3-replication/versions.tf
modules/notification/README.md
modules/notification/main.tf
modules/notification/variables.tf
modules/notification/versions.tf
versions.tf

Make the creation of SNS/SQS policies conditional based on two new variables, `create_sns_policy` and `create_sqs_policy`.
We have a use case (as I'm sure others do) where we need to send S3 bucket notifications to an external account that we don't control, and so we can't create the related SNS/SQS policies in that account (and they aren't necessary).  The rest of the notification setup is valid when using the external resource ARNs, however.
None; the variables default to `true` so behavior will be the same.
```sh
$ terraform -v
Terraform v0.12.29
+ provider.aws v3.10.0
+ provider.null v2.1.2
+ provider.random v2.3.0
```
Using the module as published failed to apply the notification due to the inability create the policy, so I added it manually and imported it.  This snippet...:
``` …
```

feat: Creating SNS/SQS policies should be optional

---

main.tf

The ELB log delivery policy creates an ARN as opposed to using the S3 resources ARN output. These results in the policy not working in gov cloud. 
https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/issues/59
I test this change in gov cloud.

Change ELB Log Delivery Policy to use ARN output

---

.gitignore
.pre-commit-config.yaml
README.md
examples/complete/README.md
examples/notification/README.md
examples/s3-replication/README.md
modules/notification/README.md

- update documentation based on latest `terraform-docs` which includes module and resource sections
- `.gitignore` updated using GitHub provided default standard + 0.14 lockfile ignore
- these are two new sections provided by [`terraform-docs` now](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.11.0)
No
N/A

chore: update documentation based on latest `terraform-docs` which includes module and resource sections

---

.pre-commit-config.yaml
README.md
examples/complete/README.md
examples/complete/versions.tf
examples/notification/README.md
examples/notification/versions.tf
examples/s3-replication/README.md
examples/s3-replication/versions.tf
modules/notification/README.md
outputs.tf
versions.tf

fix: Update syntax for Terraform 0.15

---

.github/workflows/pre-commit.yml
README.md
examples/complete/README.md
examples/notification/README.md
examples/object/README.md
examples/s3-replication/README.md
modules/notification/README.md
modules/object/README.md

- update documentation and pin `terraform_docs` version to avoid future changes
- pin version to avoid unnecessary updates when a PR coincides with a version update for `terraform_docs`
- no
- documentation change only - ci/cd should pass checks

chore: update documentation and pin `terraform_docs` version to avoid future changes

---

README.md
main.tf
versions.tf

Fixes #78
Issue in terragrunt - https://github.com/gruntwork-io/terragrunt/issues/1211

feat: Added workaround for variable type `any`

---

main.tf

Removing "${ sequence from the start and the }" aws_s3_bucket.this[0].arn to silence the warning about non-constant expressions provided via interpolation syntax
Tired of the following message:
Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.
Does this break backwards compatibility with the current major version? **No**
- I did this change locally and applied the infrastructure update referencing the local version of the code. Warning didn't show up

chore: Updated string interpolation in resource

---

examples/s3-replication/main.tf
main.tf

Completely based on #104
Fixes #104

fix: Always send `filter` map in replication config

---

README.md
examples/complete/README.md
examples/complete/main.tf
examples/complete/versions.tf
examples/notification/README.md
examples/notification/versions.tf
examples/object/README.md
examples/object/versions.tf
examples/s3-replication/README.md
examples/s3-replication/versions.tf
modules/notification/README.md
modules/notification/versions.tf
modules/object/README.md
modules/object/versions.tf
versions.tf
wrappers/notification/versions.tf
wrappers/object/versions.tf
wrappers/versions.tf

Uses the new data resource for aws_cloudfront_log_delivery_canonical_user_id that provides this field instead of using the hardcoded value.
Per this github issue: https://github.com/hashicorp/terraform-provider-aws/issues/12512 which has now been solved we can use this resource to provide this ID.
Will need to update provider to v3.6
The most recent provider has this data block
I created this on my local by running terraform plan and apply and destroy to create the new bucket which was successfully created in AWS. To test cloudfront I have used this fork and have successfully received logs in s3.

feat: Replace hardcoded cloudfront canonical user ID in example

---

.pre-commit-config.yaml
README.md
examples/s3-replication/README.md
examples/s3-replication/main.tf
examples/s3-replication/versions.tf
main.tf
versions.tf
wrappers/README.md
wrappers/main.tf
wrappers/notification/README.md
wrappers/object/README.md

This change is about taking into account the recent enhancement of the AWS Terraform Provider which now allows to set S3 Replication Time Control (RTC)
Thanks to this enhancement, we will be able to provision S3 Bucket Replication Configurations with SLAs and Metrics on the Replication itself from this terraform module.
It's the reflection on the module of the closure of the following issue : https://github.com/hashicorp/terraform-provider-aws/issues/10974
There is no breaking change since I have just added the right attributes on the Replication configuration which are read from user input in the destination block of the replication_configuration attribute.
- [X ] I have tested and validated these changes using one or more of the provided `examples/*` projects
I have adapted the …

feat: Added Replication Time Control for Bucket Replication

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
Makefile
examples/complete/README.md
examples/notification/README.md
examples/object/README.md
examples/s3-replication/README.md

- update CI workflow to use composite actions
- update pre-commit versions to latest
- update terraform-docs to latest version v0.16.0
- add new argument to `terraform_docs` hook which avoids pinning to exact version due to conflict of .terraform.lock.hcl file (https://github.com/terraform-docs/terraform-docs/pull/527)
- update Makefile to allow for breaking changes (scope) and rolling back a release
- consolidates CI actions and updates terraform-docs to latest
- no
- documentation and CI change only, no module changes

chore: Update CI workflow to use composite actions and update pre-commit versions

---

README.md
examples/complete/main.tf
main.tf
variables.tf

This adds an additional parameter that toggles whether to add a bucket policy for requiring TLS 1.2 in order to access the bucket.
I'm working in an organization that requires TLS v1.2 on all of their buckets. I was already using the module and thought this is a common enough need in secure organizations that we should generalize it. I created an issue requesting the feature here: https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/issues/125.
Fixes #125
No
I tested using the `examples/complete` project by adding the new parameter on to the buckets. I confirmed in my console that the policy was created.

feat: Added optional bucket policy for requiring TLS 1.2

---

main.tf

add lifecycle ignore changes on s3_bucket resource to prevent configuration loop to fix https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/issues/144
add lifecycle ignore changes on s3_bucket resource for all new resources that are separate to prevent configuration loop
fixes lifecycle loop
I tested it live because this is blocking my work 😞

fix: Add lifecycle ignore changes on s3_bucket resource to prevent configuration loop

---

.pre-commit-config.yaml
README.md
UPGRADE-3.0.md
examples/complete/README.md
examples/complete/main.tf
examples/complete/versions.tf
examples/notification/README.md
examples/notification/versions.tf
examples/object/README.md
examples/object/versions.tf
examples/s3-replication/README.md
examples/s3-replication/versions.tf
main.tf
variables.tf
versions.tf

It was too optimistic (and not feasible) to make it work with AWS provider version 3.75 as the lowest requirement.
AWS provider `v3.75` - the latest supported version of this module is `v3.0.1`
Fixed #148

feat: Upgraded AWS provider to 4.5, fixed object_lock_enabled

---

main.tf

Change the `hostname` key referenced by the redirect configuration on website routing rules from `hostname` to `host_name`. 
The AWS provider attribute name is `host_name`, and it's also used as `host_name` in the complete example.
No

fix: Key `host_name` on website routing rules redirect

---

modules/notification/main.tf

Impossible to use notification module only for enable/disable S3 EventBridge. You need to set at least one notification option.
PR allows setup eventbridge without adding notification options
No breaking changes. It was removed validation of length of arrays of notifications settings. Without this validation dynamic blocks  will still not executed because of empty arrays

fix: Allow setup eventbridge without notifications

---

main.tf

This one is the revert for my previous PR, I've misconfigured my local setup this is why it looked like it worked, actually it introduced another issue with multiple `access_control_policy` blocks. I am really sorry for that one.
None.

fix: Revert change for grant in aws_s3_bucket_acl resource

---

.pre-commit-config.yaml
README.md
examples/complete/README.md
examples/complete/main.tf
examples/complete/versions.tf
examples/notification/README.md
examples/notification/versions.tf
examples/object/README.md
examples/object/versions.tf
examples/s3-replication/README.md
examples/s3-replication/versions.tf
main.tf
versions.tf

This PR removes deprecated attributes from the `aws_s3_bucket` resource. This required a change to the required AWS provider version, version `4.9.0` made the removed attributes optional - this module uses the standalone resources.
I also updated one of the examples as the hard-coded value caused errors when testing.
Fixes https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/issues/174
Fixes https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/issues/177
Fixes https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/issues/176
Prior to this change, Terraform shows `Warning: Deprecated attribute` when running an apply. This no longer happens with these changes.
This fixes https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/issues/174 and …

fix: Remove deprecated attributes from ignore_changes

---

.github/workflows/lock.yml
.github/workflows/pr-title.yml
.github/workflows/pre-commit.yml
.github/workflows/release.yml
.github/workflows/stale-actions.yaml
.pre-commit-config.yaml
main.tf
wrappers/README.md
wrappers/notification/README.md
wrappers/object/README.md

- Update GitHub action versions to use latest. This remove warnings related to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- Ensure pre-commit config is aligned with latest
- Add `lock.yml` workflow to automatically lock issues and PRs after 30 days. Theres a lot "Me too" or "I have this issue, when will this get fixed" on really old/stale issues and in order to properly triage, users need to supply their configurations. This workflow is pulled from the AWS provider's repo to force users to fill out a proper issue ticket and keep chatter out of merged PRs or old issues
- Patch warnings on CI checks to keep output clean
- Focus on new issues and PRs
- No

fix: Update CI configuration files to use latest version

---

examples/complete/main.tf
main.tf

Fixes #217 
It doesn't introduce BC break, and no need for another variable

feat: Added new S3 bucket policy statement for latest regions

---

modules/notification/main.tf

Allow setting the id parameter inside the notification block.
When configuring bucket notifications using map type inside another map, like in the example [here](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/bf80a09f0955e6542a6ae8f3b7fa8fbd612148ea/examples/notification/main.tf#L145), there is no control on the order of the notifications.
This can cause terraform to change the resource and replace the notifications order after importing bucket notification, because the state contains list of sorted notifications and the map order can be different.
```terraform
sns_notifications = {
ios = {
topic_arn     = "arn:aws:sns:eu-west-1:123456789012:ios-log-upload"
events        = ["s3:ObjectCreated:*"]
filter_prefix = "ios/"
},
android = {
topic_arn     = …
```

feat: Allow setting id parameter in notification object

---

README.md
examples/complete/main.tf
main.tf
variables.tf
wrappers/main.tf

Adds attachments for deny unencrypted object uploads and incorrect encryption headers. 
Fixes https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/issues/233
Fixes https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/issues/233
No.

feat: Add "deny unencrypted object uploads" and "incorrect encryption headers" bucket policies

---

README.md
examples/complete/main.tf
main.tf
variables.tf
wrappers/main.tf

Add the possibility to specify a KMS key to use as requirement for uploading files.
See this issue #239 
No

feat: Add "deny incorrect kms key sse" bucket policy

---

main.tf

This skips executing the `data.aws_canonical_user_id.this` data source unless it is actually needed.
The data source is only needed when the `aws_s3_bucket_acl.this` resource needs to be created **and** the `var.owner["id"]` value isn't available.
As per [the `data.aws_canonical_user_id` documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/canonical_user_id), this data source requires the `s3:ListAllMyBuckets` IAM permission. Note that this permission isn't required by anything else in this module.
When the data source isn't needed, then by the [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege), we shouldn't require the `s3:ListAllMyBuckets` permission.
This additional permission is particularly obvious when …

feat: Stop requiring `s3:ListAllMyBuckets` IAM permission unless needed (for bucket ACL)

---

main.tf

This change simply adds `var.attach_access_log_delivery_policy` into the logic computing if the bucket policy should be attached or not.
This should address issue (#251).
Without this change if a bucket is being created solely for purpose of S3 access logs without any other bucket policy related flags the combined bucket policy will not be created nor attached to the bucket.
This should not break backwards compatibility.
I've tested my change with code similar to this (with bucket names changed to protect the innocent):
```
module "access_log_bucket" {
source                            = "git@github.com:brycewade1/terraform-aws-s3-bucket.git?ref=bugfix/attach-access-log-policy"
bucket                            = "s3-log-bucket-${local.region}-${local.account_id}" …
```

fix: Added missing check for attach_access_log_delivery_policy for access logs logic

---

.github/workflows/lock.yml
.github/workflows/pr-title.yml
.github/workflows/pre-commit.yml
.github/workflows/release.yml
.github/workflows/stale-actions.yaml
.pre-commit-config.yaml
UPGRADE-3.0.md

- Update CI workflow versions to remove deprecated runtime warnings
- Updates our workflows to use the latest versions
- Removes the `deprecated runtime` warnings from the workflow execution output
- No

fix: Update CI workflow versions to remove deprecated runtime warnings

---

README.md
variables.tf

Candidate for smallest PR in history 😄 just a typo I spotted earlier today when I was using this module.
I promised myself I'd come back and raise a PR for it. Scouts rule and all that!
N/A
None
N/A

fix: Typo in description of `access_log_delivery_policy_source_buckets` variable

---

.github/workflows/pr-title.yml
.github/workflows/pre-commit.yml
.pre-commit-config.yaml
README.md
examples/complete-legacy/README.md
examples/complete/README.md
examples/notification/README.md
examples/object/README.md
examples/s3-analytics/README.md
examples/s3-inventory/README.md
examples/s3-replication/README.md
modules/notification/README.md
modules/object/README.md
wrappers/notification/versions.tf
wrappers/object/versions.tf
wrappers/versions.tf

- Update CI workflow versions to latest
- Updates our workflows to use the latest versions
- Removes warnings for Python 3.12 in runners
- No

fix: Update CI workflow versions to latest

---

modules/notification/README.md
modules/notification/main.tf
modules/notification/variables.tf
wrappers/notification/main.tf

In the Notification module create a new variable a new `create_lambda_policy` that functions similar to `create_sqs_policy` and `create_sns_policy`
I define and manage my Lambda Policy separate from the Terraform where I manage my S3 Notifications. I don't want this module to force me to manage the Lambda policy here.
Fixes #301 
I think that migrating `aws_lambda_permission.allow` from a single to a `count` this will cause the Resource to be recreated.
This can be avoided by performing [`terraform state mv`](https://developer.hashicorp.com/terraform/cli/commands/state/mv)
There are 3 types of notifications, and this change brings Lambda in line with SQS and SNS that support `create_sqs_policy` and `create_sns_policy`

feat: Add variable create_lambda_permission in notification module

---

README.md
examples/complete/main.tf
main.tf
variables.tf
wrappers/main.tf

There have been incidents where leaked credentials have led to attackers encrypting S3 buckets with their own keys in a form of ransomware attack. AWS recommends implementing policy to prevent using SSEC if that is not a feature that you use in a given bucket. This PR adds an optional policy attachment that implements AWS' recommendation.
Reference:
https://aws.amazon.com/blogs/security/preventing-unintended-encryption-of-amazon-s3-objects/
Enable users to easily block the use of SSEC in their buckets, mitigating a potential avenue of attack in the event of leaked credentials.
I have updated one of the examples, but I won't be able to test it until later.  I will try to follow up soon with the results.

feat: Add optional policy to deny ssec encrypted uploads

---

README.md

remove `acl` setting from ALB/NLB example in readme file
The [Terraform AWS Provider Version 4 Upgrade Guide](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade#acl-argument) states that the `acl` argument should be removed from the `aws_s3_bucket` resource
No. This is a change to a readme file
n/a change is only to a readme file
n/a change is only to a readme file
n/a change is only to a readme file

docs: Remove acl setting from ALB/NLB example in readme file

---

.pre-commit-config.yaml
modules/notification/main.tf

Add explicit IAM policy version (`"2012-10-17"`) to SQS policy in notification module to avoid API timeout during apply when modifying the resource. Very simple change to add what is already a default for the resource.
Solution discovered in documentation while attempting to troubleshoot the issue (big ol' warning under the resource overview): [Resource: aws_sqs_queue](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue)
Error:
```
╷
│ Error: waiting for SQS Queue (https://sqs.us-west-2.amazonaws.com/<redacted>) attribute (Policy) create: timeout while waiting for state to become 'equal' (last state: 'notequal', timeout: 19m59.970811759s)
│ 
│   with module.ingest_bucket_notifications["cloudflare"].aws_sqs_queue_policy.allow["<redacted>"],
│   on …
```

fix: Timeout if SQS policy created without explicit version in notification module

---

outputs.tf

Use the id of the s3 bucket or the directory bucket instead of the policy. 
When attaching a policy after the bucket creation, any resource dependent on the output `s3_bucket_id` will show needing modified and possibly destroyed and recreated. This change will use the bucket resources directly to determine the bucket id instead of reading the policy first. 
- [ No Changes ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ X ] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [ X ] I have executed `pre-commit run -a` on my pull request

fix: Include `aws_s3_directory_bucket` ID in `s3_bucket_id` output

---

README.md
outputs.tf

When creating replicated buckets, expose a versioning status output in order to be able to create a dependency on replica buckets being ready (versioning enabled). Otherwise applying replication rules targeting a bucket which isn't fully set up may fail.
There is no data source for bucket versioning status or exposed attributes for versioning except the `aws_s3_bucket_versioning` resource which is currently encapsulated by this module.
Take the following (abbreviated) example:
```terraform
module "bucket" {
source  = "terraform-aws-modules/s3-bucket/aws"
version = "5.2.0"
bucket = "my-bucket"
replication_configuration = {
....
}
versioning = {
enabled = true
}
}
module "replica_bucket" {
source  = "terraform-aws-modules/s3-bucket/aws"
version = "5.2.0"
bucket = "my-bucket-replica" …
```

feat: Add bucket versioning status as an output
